spring:
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server: 
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

logging:
  config: "classpath:logback.xml"

