server:
  port: 9018

spring:
  application:
    name: product-server
  redis:
    hostName: 120.26.130.187
    port: 6379
    timeout: 20000
    password: jsy2017++
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  datasource:
    sql:
      show: false
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://18.16.200.42:3306/zss_st?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=round&allowMultiQueries=true
    username: root
    password: shitou$root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20  
  jpa:
    database: MYSQL    
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache: 
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          provider_configuration_file_resource_path: ehcache.xml
logging:
  config: ${spring.config.location}/logback.xml
#ribbon超时配置
ribbon:
  #读取超时
  ReadTimeout: 60000
  #连接超时
  ConnectTimeout: 30000
feign:
  hystrix:
    enabled: true